services:
  media_api:
    build:
      dockerfile: Dockerfile
    container_name: media_api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8080"
    depends_on:
      azure_blob_storage:
        condition: service_started
    restart: on-failure

  azure_blob_storage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azure_blob_storage
    command: "azurite-blob --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
    volumes:
      - azure_blob_storage_data:/data

volumes:
  azure_blob_storage_data:

networks:
  default:
    external:
      name: api_net