services:
  media_api:
    build:
      dockerfile: Dockerfile
    container_name: media_api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8080"
    depends_on:
      azurite_media_api:
        condition: service_started
    restart: on-failure

  azurite_media_api:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: blob_storage_media_api
    command: "azurite-blob --blobHost 0.0.0.0"
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data: