spring:
  datasource:
    url: jdbc:postgresql://postgresql_media_api:5432/mediadb
    username: IgnacioVillarreal
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: rabbitmq_media_api
    port: 5672
    username: IgnacioVillarreal
    password: 12345678

azure:
  blob-storage:
    connection-string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCD+==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    container-name: images
