spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

azure:
  blob-storage:
    connection-string: ${AZURE_BLOB_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_BLOB_STORAGE_CONTAINER_NAME}

rabbitmq:
  exchange: RescueMeExchange
  queue:
    create: RescueMeCreateImageQueue
    delete: RescueMeDeleteImageQueue
    deleteAll: RescueMeDeleteImagesQueue
  routing-key:
    create: RescueMeCreateImageRoutingKey
    delete: RescueMeDeleteImageRoutingKey
    deleteAll: RescueMeDeleteImagesRoutingKey