spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/main_db
    username: ignacio
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: media_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ignacio
    password: 12345678

  flyway:
    enabled: true
    schemas: auth_api
    locations: classpath:db/migration

azure:
  blob-storage:
    connection-string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCD+==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    container-name: images

cors:
  allowed-origins:
    - http://localhost:4200/

logging:
  level:
    org:
      springframework:
        security: DEBUG
